name: Barrington Creative
favicon: null
layout_spectrum: 0.8707372636999935
typography_spectrum: 0.04773161746561527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.40380072244443
  lightness: 0.5289226747117937
  saturation: 0.983790148049593
  rhythmicContrast: 0.7577169602736831
purpose: []
